FROM denoland/deno:alpine

# Prefer not to run as root.
USER deno

WORKDIR /app

COPY . . 

# Compile the main app so that it doesn't need to be compiled each startup/entry.
RUN deno cache --import-map=import_map.json ./src/server/index.ts

EXPOSE 80
CMD ["run", "--import-map=import_map.json", "--allow-all", "./src/server/index.ts"]

